"""Data health audit for the stock-analysis monorepo output directories.

Checks Individual_Stocks/, Sector/, scores.json, and Sector_Combined.csv.
Read-only: writes nothing, calls no LLM, hits no network.

Usage:  .venv\\Scripts\\python.exe .claude\\skills\\data-doctor\\doctor.py

Exit code = number of ERROR-level findings.
"""
import datetime
import glob
import json
import math
import os
import sys

sys.stdout.reconfigure(encoding="utf-8", errors="replace")

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
sys.path.insert(0, os.path.join(ROOT, "Full App"))

from backend.services.individual_service import (  # noqa: E402
    extract_overall_score, extract_credibility_score, assign_signal,
)

IND = os.path.join(ROOT, "Individual_Stocks")
SEC = os.path.join(ROOT, "Sector")
SCORES_JSON = os.path.join(ROOT, "scores.json")
COMBINED = os.path.join(SEC, "Sector_Combined.csv")

VALID_SUFFIXES = (".txt", "_concall.txt", "_concall_score.txt")
STALE_DAYS = 90
SIZE_LIMIT_KB = 100

findings = []  # (severity, area, message)


def add(sev, area, msg):
    findings.append((sev, area, msg))


def age_days(path):
    return (datetime.datetime.now()
            - datetime.datetime.fromtimestamp(os.path.getmtime(path))).days


# ── 1. Individual_Stocks ─────────────────────────────────────────────────
overall, credibility = {}, {}
if not os.path.isdir(IND):
    add("ERROR", "individual", f"missing directory: {IND}")
else:
    files = [f for f in os.listdir(IND) if f.endswith(".txt")]
    companies = sorted(f[:-4] for f in files
                       if "_" not in f[:-4] and f != "CLAUDE.md")

    # filename convention violations (anything _* that isn't a valid suffix)
    for f in files:
        stem = f[:-4]
        if "_" in stem and not (f.endswith("_concall.txt") or f.endswith("_concall_score.txt")):
            add("ERROR", "individual",
                f"filename violates underscore convention (corrupts dashboards): {f}")

    for c in companies:
        base = os.path.join(IND, c + ".txt")
        concall = os.path.join(IND, c + "_concall.txt")
        cscore = os.path.join(IND, c + "_concall_score.txt")

        s = extract_overall_score(base)
        if s is None:
            add("ERROR", "individual", f"{c}: overall score NOT extractable from {c}.txt")
        else:
            overall[c] = s

        if not os.path.exists(concall):
            add("WARN", "individual", f"{c}: missing _concall.txt (pipeline incomplete)")
        else:
            txt = open(concall, encoding="utf-8", errors="replace").read()
            if "LLM SYNTHESIS" in txt:
                add("INFO", "individual",
                    f"{c}: Walk-the-Talk is NOT search-grounded (synthesis fallback) — "
                    f"concall score is LOW confidence")

        if not os.path.exists(cscore):
            add("WARN", "individual", f"{c}: missing _concall_score.txt")
        else:
            cs = extract_credibility_score(cscore)
            if cs is None:
                add("ERROR", "individual",
                    f"{c}: credibility score NOT extractable from _concall_score.txt")
            else:
                credibility[c] = cs

        for p in (base, concall, cscore):
            if os.path.exists(p) and os.path.getsize(p) / 1024 > SIZE_LIMIT_KB:
                add("WARN", "individual",
                    f"{os.path.basename(p)}: {os.path.getsize(p)/1024:.0f} KB "
                    f"(> {SIZE_LIMIT_KB} KB pipeline guard)")
        if age_days(base) > STALE_DAYS:
            add("INFO", "individual", f"{c}: analysis is {age_days(base)} days old")

    # orphans: companions without a base file
    for f in files:
        for suf in ("_concall.txt", "_concall_score.txt"):
            if f.endswith(suf):
                c = f[: -len(suf)]
                if not os.path.exists(os.path.join(IND, c + ".txt")):
                    add("WARN", "individual", f"orphan {f}: no {c}.txt base analysis")

# ── 2. scores.json consistency ───────────────────────────────────────────
if not os.path.exists(SCORES_JSON):
    add("WARN", "scores.json", "missing (regenerated by dashboards / individual API)")
else:
    try:
        saved = json.load(open(SCORES_JSON, encoding="utf-8"))
        for key, fresh in [("overall_scores", overall), ("credibility_scores", credibility)]:
            got = saved.get(key)
            if got is None:
                add("ERROR", "scores.json", f"missing top-level key: {key}")
                continue
            for c, v in fresh.items():
                if c not in got:
                    add("WARN", "scores.json", f"{key}: '{c}' missing (file is newer — regenerate)")
                elif abs(float(got[c]) - float(v)) > 0.05:
                    add("ERROR", "scores.json",
                        f"{key}: '{c}' saved={got[c]} but file extracts to {v}")
            for c in got:
                if c not in fresh:
                    add("WARN", "scores.json",
                        f"{key}: '{c}' present but its file is gone/unextractable — regenerate")
    except (json.JSONDecodeError, ValueError) as e:
        add("ERROR", "scores.json", f"unparseable: {e}")

# ── 3. Sector folders ────────────────────────────────────────────────────
sector_floor = {}   # sector CSV's Sector value -> floor threshold
if not os.path.isdir(SEC):
    add("ERROR", "sector", f"missing directory: {SEC}")
else:
    for item in sorted(os.listdir(SEC)):
        folder = os.path.join(SEC, item)
        if not os.path.isdir(folder):
            continue
        csvs = glob.glob(os.path.join(folder, "*.csv"))
        txts = [f for f in os.listdir(folder) if f.endswith(".txt") and not f.endswith("_Score.txt")]
        scores_txt = [f for f in os.listdir(folder) if f.endswith("_Score.txt")]

        if os.path.exists(os.path.join(folder, "progress.json")):
            add("INFO", "sector", f"{item}: progress.json present (Phase 7 resumable/incomplete)")
        if not csvs:
            if txts or scores_txt:
                add("WARN", "sector", f"{item}: has .txt data but no CSV (pipeline stopped early)")
            continue

        for cf in csvs:
            try:
                import pandas as pd
                df = pd.read_csv(cf)
            except Exception as e:
                add("ERROR", "sector", f"{os.path.basename(cf)}: unreadable CSV ({e})")
                continue
            missing_cols = {"company", "score"} - set(df.columns)
            if missing_cols:
                add("ERROR", "sector", f"{os.path.basename(cf)}: missing columns {missing_cols}")
                continue
            bad = df[(df["score"] < 0) | (df["score"] > 100)]
            if len(bad):
                add("ERROR", "sector",
                    f"{os.path.basename(cf)}: {len(bad)} score(s) outside 0-100")
            if len(df):
                mx = df["score"].max()
                if "Sector" in df.columns and len(df["Sector"]):
                    sector_floor[str(df["Sector"].iloc[0])] = math.floor(mx / 10) * 10

        if len(txts) and len(scores_txt) < len(txts):
            add("INFO", "sector",
                f"{item}: {len(txts)} extractions but only {len(scores_txt)} _Score.txt "
                f"(Phase 6 incomplete — rerun resumes from cache)")

# ── 4. Sector_Combined.csv ───────────────────────────────────────────────
if os.path.exists(COMBINED):
    try:
        import pandas as pd
        comb = pd.read_csv(COMBINED)
        if list(comb.columns) != ["company", "score", "Sector", "url"]:
            add("WARN", "combined", f"columns are {list(comb.columns)} "
                                    f"(expected company,score,Sector,url)")
        for sector, grp in comb.groupby("Sector"):
            if sector not in sector_floor:
                add("WARN", "combined",
                    f"stale rows: sector '{sector}' has no source folder/CSV anymore — "
                    f"regenerate via run_csv_combiner()")
            elif (grp["score"] < sector_floor[sector]).any():
                add("ERROR", "combined",
                    f"sector '{sector}': rows below floor {sector_floor[sector]} "
                    f"(floor(max/10)*10 rule violated — regenerate)")
    except Exception as e:
        add("ERROR", "combined", f"unreadable: {e}")
else:
    add("INFO", "combined", "Sector_Combined.csv missing (regenerated by ScoreVisualApp/Full App)")

# ── Report ───────────────────────────────────────────────────────────────
order = {"ERROR": 0, "WARN": 1, "INFO": 2}
findings.sort(key=lambda f: (order[f[0]], f[1]))
counts = {s: sum(1 for f in findings if f[0] == s) for s in order}

print(f"\n{'='*74}\nDATA DOCTOR — {ROOT}")
print(f"companies: {len(overall)} financial / {len(credibility)} credibility scores extracted")
print(f"findings : {counts['ERROR']} ERROR, {counts['WARN']} WARN, {counts['INFO']} INFO\n{'='*74}")
for sev, area, msg in findings:
    print(f"[{sev:<5}] {area:<12} {msg}")
if not findings:
    print("All clean.")
sys.exit(min(counts["ERROR"], 99))
